config/routes.rb
Eventapp::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  match 'twitter' => 'pages#twitter'

  match 'about' => 'pages#about'

  match 'schedule' => 'schedule_items#index'

  match 'news' => 'news#index'

  match 'map' => 'geolocations#index'
  match 'map/:id' => 'geolocations#show'
      
  match 'locationjson' => 'geolocations#location_json'

  root :to => 'pages#home'

  match ':title' => 'pages#show'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :description, :end, :organizer, :start, :title, :twitter_hashtag

  def short_description
    maxlength = 32
    (self.description[0...maxlength] || "") + (self.description.length > maxlength ? "..." : "")
  end
end

app/models/geolocation.rb
class Geolocation < ActiveRecord::Base
  attr_accessible :address, :info, :latitude, :longitude, :name
  after_validation :geocode, :if => :address_changed?
  validates :name, :presence => true
  validates :address, :presence => true
  has_many :schedule_item, :dependent => :nullify

  def short_info
    maxlength = 32
    (self.info[0...maxlength] || "") + (self.info.length > maxlength ? "..." : "")
  end

  # used in dashboard so it can grouped with other object types
  def title
    name
  end

  geocoded_by :address
end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :author, :content, :is_published, :published_at, :title
  before_save :check_for_publish
  validates :title, :presence => true
  

  def short_content
    maxlength = 32
    (self.content[0...maxlength] || "") + (self.content.length > maxlength ? "..." : "")
  end

  private
    def check_for_publish
      if id
        @is_published = News.find(id).is_published
      else
        @is_published = false
      end

      if self.is_published == true && @is_published == false
        self.published_at = Time.now
      end
      if self.is_published == false && @is_published == true
        self.published_at = nil
      end
    end
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :content, :title


  # this turns the title into something url-friendly before saving
  before_validation { |page| page.title = page.title.downcase.gsub(' ', '-') }
  validates :title, :uniqueness => true
  validates :title, :presence => true
  validates_format_of :title, :without => /\//, :message => "Cannot use forward slash in titles."
  validates_exclusion_of :title,
                         :in => ["admin", "news", "map", "locations",
                          "schedule", "twitter", "about", "locationjson"],
                          :message => "That page title is reserved."

  # this makes it Title Case again
  def pretty_title
    self.title.gsub('-', ' ').titlecase
  end

  def short_content
    maxlength = 32
    (self.content[0...maxlength] || "") + (self.content.length > maxlength ? "..." : "")
  end
end

app/models/schedule_item.rb
class ScheduleItem < ActiveRecord::Base
  belongs_to :geolocation
  attr_accessible :end, :info, :location, :map_url, :name, :start, :geolocation_id

  validates :name, :presence => true
  validates :start, :presence => true


  def short_info
    maxlength = 32
    (self.info[0...maxlength] || "") + (self.info.length > maxlength ? "..." : "")
  end

  # used in dashboard so it can grouped with other object types
  def title
    name
  end

  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/geolocations_controller.rb
class GeolocationsController < ApplicationController
  def index
    @locations = Geolocation.all
    # if Geolocation.first
    #   @latitude = Geolocation.first.latitude
    #   @longitude = Geolocation.first.longitude
    # else
    #   @latitude, @longitude = 0, 0
    #   flash[:alert] = "No map locations loaded."
    # end
  end

  def show
    @location = Geolocation.find(params[:id])
  end

  def location_json
    @all_info = Geolocation.all

    @all_locations = []

    @all_info.each do |location|
      @all_locations << [location.name, location.latitude, location.longitude]
    end

    respond_to do |format|
      format.json { render json: @all_locations }
    end
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    @news = News.order(:published_at).where("is_published = ?", true).reverse
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.find_by_title(params[:title])
    if @page == nil
      flash[:notice] = "Page not found"
      redirect_to root_path
    end
  end
  def twitter
    # @hashtag = "##{Event.first.twitter_hashtag}" || "#quickevents"
  end
  def home
    @pages = Page.all
  end
  def about
    @event_info = Event.first
  end
end

app/controllers/schedule_items_controller.rb
class ScheduleItemsController < ApplicationController
  def index
    @schedule = ScheduleItem.order(:start)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def pretty_time(time)
    time.strftime("%-l:%M %P")
  end

  def pretty_date(date)
    date.strftime("%A, %B %e, %Y")
  end

  def pretty_quick_date(date, joiner = "/")
    return_string = []
    return_string << date.strftime("%-m")
    return_string << date.strftime("%e")
    return_string << date.strftime("%y")
    
    return_string.join(joiner).gsub(" ", "")
  end
  def event_info
    @event_info = Event.first || Event.new(:title => "Untitled Event", :twitter_hashtag => "events")
    # if @event_info == "Empty"
    #   return "Untitled Event"
    # else
    # end
  end
  # def event_hashtag
  #   Event.first.twitter_hashtag || ""
  # end
end

app/helpers/geolocations_helper.rb
module GeolocationsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/schedule_items_helper.rb
module ScheduleItemsHelper
end

app/views/geolocations/index.html.erb
<div class="quickevent row">
	<h1 class="title six mobile-two columns"><a href="/"><%= event_info.title %></a></h1>
	<h4 class="six mobile-two columns"><span class="radius label">Quick Event App</span></h4>
</div>
<header class="row">
	<!-- <h1 class="title"><a href="/"><%= event_info %></a></h1>	 -->
	<h1>Locations</h1>
	<hr style="margin: 0 -15px">
</header>

<div id="wrapper">
	<section class="home-nav">
		<ul>
		<% @locations.each do |location| %>
			<li class="row"><%= link_to location.name, "/map/#{location.id}" %></li>
		<% end %>
		</ul>
	</section>
</div>

app/views/geolocations/show.html.erb
<div class="quickevent row">
  <h1 class="title six mobile-two columns"><a href="/"><%= event_info.title %></a></h1>
  <h4 class="six mobile-two columns"><span class="radius label">Quick Event App</span></h4>
</div>
<header class="row">
  <!-- <h1 class="title"><a href="/"><%= event_info %></a></h1>  -->
  <h1><%= @location.name %></h1>
  <hr>  
</header>

<section class="location row" style="padding-bottom: 20px;">
  <% if @location.longitude && @location.latitude %>
    <%= link_to(image_tag("http://maps.googleapis.com/maps/api/staticmap?" +
            "center=#{@location.latitude},#{@location.longitude}" +
            "&zoom=15&size=500x200" +
            "&markers=color:red%7C#{@location.latitude},#{@location.longitude}" + 
            "&sensor=false"),
            "http://maps.google.com/?q=#{@location.address}") %>
  <% end %>
  <h3>Address:</h3>
  <p class="address"><%= @location.address %></p>
  <h3>Infomation:</h3>
  <p class="info"><%= simple_format @location.info %></p>
  <h3>Directions to:</h3>
  <p class="direction"><%= link_to "#{@location.name}", "https://maps.google.com/maps?saddr=current+location&daddr=#{@location.address}&target=blank", :class => "small button secondary round" %></p>
  <hr style="border-top: none;">
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
	
	<!-- Uncomment to make IE8 render like IE7 -->
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
	
	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width" />
	
	<title><%= content_for?(:title) ? yield(:title) :  event_info.title || "QuickEvent" %></title>
  
	<!-- Included CSS Files -->
	<link href='http://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>
	<%= stylesheet_link_tag    "application" %>
	
	<!-- Included JS Files  -->
  <script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBTNt517NAlXasQH2iIh2qF1zZIV9Alo3s&sensor=true">
  </script>
	<%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
</head>
<body>

  <!-- dumps out all flash messages. START  -->
	<div id="flash"> 
	  <% flash.each do |flash_type, value| %>
	    <div class="subflash" id = "flash_<%=flash_type%>">
	      <%= value %>
	    </div>
	  <% end %>
	</div>
  <!-- dumps out all flash messages. END  -->

  <%= yield %>

  <footer class="row">
  	<p>Copyright 2013 Quick Event App</p>
  </footer>
  
</body>
</html>

app/views/news/index.html.erb
<div class="quickevent row">
	<h1 class="title six mobile-two columns"><a href="/"><%= event_info.title %></a></h1>
	<h4 class="six mobile-two columns"><span class="radius label">Quick Event App</span></h4>
</div>
<header class="row">
	<!-- <h1 class="title"><a href="/"><%= event_info %></a></h1>	 -->
	<h1>News</h1>
	<hr>	
</header>
<section class="news row" style="padding-bottom: 20px;">
  <% @news.each do |item| %>
  	<div>
	    <h3><%= item.title %></h3> 
	    <p><%= "#{pretty_time(item.published_at)} on #{pretty_quick_date(item.published_at)}" || item.created_at %></p>
	    <p><%= item.content %></p>
    </div>
  <% end %>
</section>

app/views/pages/about.html.erb
<div class="quickevent row">
	<h1 class="title six mobile-two columns"><a href="/"><%= event_info.title %></a></h1>
	<h4 class="six mobile-two columns"><span class="radius label">Quick Event App</span></h4>
</div>
<header class="row">
	<!-- <h1 class="title"><a href="/"><%= event_info %></a></h1>	 -->
	<h1>About</h1>
	<hr>	
</header>
<section class="row" style="padding-bottom: 20px;">
	<h3>Organizer:</h3>
	<p><%= @event_info.organizer %></p>
	<h3>When:</h3>From: <%= pretty_time(@event_info.start) %> on <%= pretty_date(@event_info.start) %>   <br>To: <%= pretty_time(@event_info.end) %> on <%= pretty_date(@event_info.end) %></p>
	<h3>About the Conference:</h3>
	<p><%= @event_info.description %></p>
	<hr style="border-top: none;">
</section>

app/views/pages/home.html.erb
<div class="quickevent row">
	<h1 class="title six mobile-two columns"><a href="/"><%= event_info.title %></a></h1>
	<h4 class="six mobile-two columns"><span class="radius label">Quick Event App</span></h4>
</div>
<img src="/assets/wizard.png" style="margin-bottom: -3px; width: 100%;">

<header class="row">
	<!-- <h1 class="title"><a href="/"><%= event_info %></a></h1> -->
	<!-- <h1>Home</h1> -->

	<hr style="margin: 0 -15px">
</header>
<div id="wrapper">
	<section class="home-nav">
		<ul>
			<li class="row"><%= link_to "Schedule", schedule_path %></li>
			<li class="row"><%= link_to "About", about_path %></li>
			<li class="row"><%= link_to "Twitter", twitter_path %></li>
			<li class="row"><%= link_to "Map", map_path %></li>
			<li class="row"><%= link_to "News", news_path %></li>
			<% if APP["pages_on"] == true %>
				<% @pages.each do |page| %>
	  			<li class="row"><%= link_to page.pretty_title, "/#{page.title}" %></li>
				<% end %>
			<% end %>
		</ul>
	</section>
</div>

app/views/pages/show.html.erb
<div class="quickevent row">
  <h1 class="title six mobile-two columns"><a href="/"><%= event_info.title %></a></h1>
  <h4 class="six mobile-two columns"><span class="radius label">Quick Event App</span></h4>
</div>
<header class="row">
  <h1><%= @page.pretty_title %></h1>
  <hr>  
</header>
<section class="page row">
  <%= simple_format @page.content %>
</section>

app/views/pages/twitter.html.erb
<%= content_tag "script", nil, { :type => "text/javascript", :src => "//platform.twitter.com/widgets.js" } %>
<div class="quickevent row">
	<h1 class="title six mobile-two columns"><a href="/"><%= event_info.title %></a></h1>
	<h4 class="six mobile-two columns"><span class="radius label">Quick Event App</span></h4>
</div>


<header class="row">
	<!-- <h1 class="title"><a href="/"><%= event_info %></a></h1>	 -->
	<h1>#wizcon</h1>
<!-- Here's the tweet button -->
	<%=content_tag "a", "Tweet", :class => "small button round secondary", :href =>"https://twitter.com/intent/tweet?hashtags=#{event_info.twitter_hashtag}"%>
<!-- END Tweet button -->

	<hr>

</header>

<section class="twitter row">
	<ul>
	<% Twitter.search("##{event_info.twitter_hashtag}", :count => 10, :result_type => "recent").results.map do |status| %>
	  <li>
	    <%= content_tag "strong", status.from_user %>: <%= status.text %>
			<br />
			<div style="padding: 20px 0;">
	    <%= content_tag "a", "Reply", :class => "small button round secondary mobile-one push-one-mobile", :href => "https://twitter.com/intent/tweet?in_reply_to=#{status.id}&hashtags=#{event_info.twitter_hashtag}" %>
	    <%= content_tag "a", "Retweet", :class => "small button round secondary mobile-one push-one-mobile", :href => "https://twitter.com/intent/retweet?tweet_id=#{status.id}" %>
	    <%= content_tag "a", "Favorite", :class => "small button round secondary mobile-one push-one-mobile end", :href => "https://twitter.com/intent/favorite?tweet_id=#{status.id}" %>
	    	</div>
	  </li>
	<% end %>
	</ul>
</section>

<!-- 

<p><a href="https://twitter.com/intent/tweet?in_reply_to=51113028241989632">Reply</a></p>
<p><a href="https://twitter.com/intent/retweet?tweet_id=51113028241989632">Retweet</a></p>
<p><a href="https://twitter.com/intent/favorite?tweet_id=51113028241989632">Favorite</a></p> -->

app/views/schedule_items/index.html.erb
<div class="quickevent row">
	<h1 class="title six mobile-two columns"><a href="/"><%= event_info.title %></a></h1>
	<h4 class="six mobile-two columns"><span class="radius label">Quick Event App</span></h4>
</div>
<header class="row">
	<!-- <h1 class="title"><a href="/"><%= event_info %></a></h1> -->
	<h1>Schedule</h1>
	<hr>
</header>
<section class="schedule row" style="padding-bottom: 20px;">
	<% @schedule.each do |item| %>
		<div>
		    <h3><%= item.name %></h3>
		    <p><%= pretty_time(item.start) %> on <%= pretty_quick_date(item.start) %> —
		       <%= pretty_time(item.end) %> on <%= pretty_quick_date(item.end) %></p>

		    <p><%= item.info %></p>
		    <h4>Location:</h4>
		    <p><%=content_tag "a", "#{item.geolocation.name}", :class => "small button round secondary", :href =>"map/#{item.geolocation.id}"%></p>

		</div> 
	<% end %>
</section>